Стилизация
htmlacademy-htmlcss/2287845-sedona-36 pull request #4
Opened 2023-02-04 17:50 UTC by U1ix

2023-02-05 11:20 UTC, DKukushkin91 requested changes

2023-02-05 11:20 UTC, DKukushkin91 commented on styles/styles.css
> +  background-image: url("../images/background-mountains.jpg");
![изображение](https://user-images.githubusercontent.com/62586082/216814715-18390a0e-beda-4d2e-be36-2eaaae348f76.png)

- [ ] Нужно объеденить 2 картинки и вставить вместе фоном.

2023-02-05 11:20 UTC, DKukushkin91 commented on styles/styles.css
> +@font-face {
что бы не описывать каждый раз #000000 хекс код цвета, лучше создать вверху файла css переменные и обращаться к ним.

:root {
  --black: #000000;
  }

и далее получаем цвет через var(--black);

и т.д

2023-02-05 11:20 UTC, DKukushkin91 commented on styles/styles.css
> +}
- [ ] На странице у секций заголовки одинаковы. Лучше будет задать им единый класс и стилизовать его. 

Касается **всех** подобных заголовков

![изображение](https://user-images.githubusercontent.com/62586082/216815455-e875d360-b256-4dff-91b6-c9dbc38f4ba8.png)

2023-02-05 11:20 UTC, DKukushkin91 commented on styles/styles.css
> +.advantage-list {
- [ ] Отсутствует стилизация фонов в элементах списка.
![изображение](https://user-images.githubusercontent.com/62586082/216815529-bd5c9257-a5b6-49d7-aa04-20bb4f76616b.png)

2023-02-05 11:20 UTC, DKukushkin91 commented on styles/styles.css
> +.features {
- [ ] у списка нет фонов 

![изображение](https://user-images.githubusercontent.com/62586082/216815558-e4ba6d04-8cb1-4727-b569-7ff6e976a7d1.png)

2023-02-05 11:20 UTC, DKukushkin91 commented on styles/styles.css
> +}
Не понимаю 1-ого, ты создал пул реквест, значит считаешь, что задание готово к проверке. При этом почему то сделал его частично. Необходимо было стилизовать вообще **все** текстовые элементы как в макете, а по факту сделана часть главной страница, а страница с каталогом вообще не сделана.

2023-02-05 16:51 UTC, U1ix commented on styles/styles.css
> +}
блин) я про католог вообще забыл) хД

2023-02-06 19:33 UTC, U1ix commented
Чет не получается комитить (новый код)

2023-02-06 19:34 UTC, U1ix reviewed
ГГ

2023-02-08 16:35 UTC, DKukushkin91 requested changes

2023-02-08 16:35 UTC, DKukushkin91 commented on styles/styles.css
> +  background-image: url("../images/Group 37.jpg");
welcome-background есть у тебя файл, его подключи а этот удали.

2023-02-08 16:35 UTC, DKukushkin91 commented on styles/styles.css
> +  background-image: url("../images/Group 37.jpg");
для background хорошо бы указать размеры. В нашем случае это background-size: cover, благодаря этому фон заполнит полностью родительский блок

2023-02-08 16:41 UTC, merged