5й раздел
htmlacademy-htmlcss/2287845-sedona-36 pull request #6
Opened 2023-02-13 13:05 UTC by U1ix

5й раздел

2023-02-25 19:09 UTC, U1ix commented
5й раздел Каталог

2023-02-25 19:16 UTC, U1ix commented
ыы

2023-02-25 19:32 UTC, U1ix reviewed
ГГ

2023-02-25 19:33 UTC, U1ix commented
Как

2023-02-25 19:45 UTC, U1ix commented
ф

2023-03-03 12:36 UTC, U1ix commented
Проверка

2023-03-06 17:16 UTC, DKukushkin91 requested changes

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +button {
запрещено задавать тегам стили. Это должен быть класс .button

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  height: 100%;
min-height: 100vh

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  min-height: 100vh;
все стили в body заменить на:
      
        margin: 0;
        min-height: 100vh;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  max-width: 1280px;
все стили в .container поменять на:

      padding: 0 40px;
      background-color: #F2F2F2;
      display: flex;
      flex-direction: column;
      min-height: 100vh;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  flex: 1 0 auto;
всё заменить на:
      
        box-shadow: 0 -15px 15px rgba(0, 0, 0, 0.2);
        background: #FFFFFF;
        margin: 0 auto;
        max-width: 1200px;
        font-family: "PT Sans", sans-serif;
        font-size: 22px;
        line-height: 26px;
        color: black;
        flex: 1 0 auto;
        position: relative;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  min-width: 339px;
`min-width` убрать

Добавить `column-gap: 40px;`

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  height: 485px;
`height` нужно заменить на `min-height`

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  text-align: -webkit-center;
это что вообще? `text-align: center `

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  margin-bottom: 21px;
этот margin не нужен

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 69px 0 69px 0;
добавить `width: 100%; max-width: 651px; margin: 0 auto 90px auto;`
убрать `padding`

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  top: 0;
top: -1px

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  min-width: 400px;
Убери `min-width`

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  margin: 0;
сравни цвет текста у тебя и в макете. И сделай по макету

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  min-width: 400px;
так же добавь.
    
    width: 100%;
    max-width: 230px;
    margin: 0 auto;
    padding: 100px 0;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  max-width: 400px;
смени стили на:

    background-color: rgba(131, 179, 211, 0.2);
    width: 100%;
    max-width: 400px;
    display: flex;
    justify-content: center;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  background-color: #82B3D3;
смени стили на:

      background-color: #82B3D3;
      color: #FFFFFF;
      justify-content: space-between;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 64px 0 64px 0;
добавь 

    width: 100%;
    max-width: 505px;
    margin: 0 auto;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +
.features-subtitle добавь в стили и задай верный цвет тексту

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +
добавь в стили сюда.

      .offer .section {
            width: 100%;
            max-width: 592px;
            margin: 0 auto;
      }

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  line-height: 36px;
добавь 

      width: 100%;
      max-width: 376px;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  padding: 0 0 54px;
вместо паддинга тут нужен margin: 0 0 54px; ведь мы отступаем от других элементов .

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
сюда добавь
    
    .subscribe .section {
        width: 100%;
        max-width: 475px;
    }

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +.page-footer-container {
эти стили должны быть просто в .page-footer а этот класс нужно удалить

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  margin: 40px 0 30px;
это padding а не margin

2023-03-06 17:16 UTC, DKukushkin91 commented on index.html
> +    <div class="page-footer-container">
убрать вообще эту разметку. Самого футера достаточно.

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
>    background-repeat: no-repeat;
у subscribe-bg должна быть только фоновая картинка и цвет текста. Остальное нужно убрать

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  margin: 0 auto;
Добавь

width: 100%;
max-width: 684px;

2023-03-06 17:16 UTC, DKukushkin91 commented on catalog.html
> +      <section class="section-subscribe">
нужно взять этот блок полностью из страницы index.html убрать только класс subscribe-bg

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  height: 21px;
height убрать.

Иначе не проходишь по критерию на переполнение контентом, всё едет.

![изображение](https://user-images.githubusercontent.com/62586082/223181572-27441249-aa1f-4d79-a51b-950053e32ec9.png)

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  width: 300px;
width: 100%;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  height: 37px;
Никогда не используй height в текстовых блоках. Убирай

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  font-size: 20px;
margin и padding замени на это:
    
    padding: 40px 0 0 0;
    border: 1px solid #E6E6E6;
    margin: 0 0 60px 0;

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +.pagination-item:nth-child(6) .pagination-link {
вообще убрать. А будет 300 страниц, ты будешь каждую искать для паддингов?

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
добавь

    .pagination-item {
        width: 60px;
        height: 60px;
    }

2023-03-06 17:16 UTC, DKukushkin91 commented on styles/styles.css
> +  height: 60px;
измини width и height на 

      width: 100%;
      height: 100%;

2023-03-06 17:28 UTC, U1ix commented on styles/styles.css
> +  height: 485px;
тут не понятно где

2023-03-06 17:39 UTC, U1ix commented on styles/styles.css
> +
Не понятно

2023-03-06 17:43 UTC, U1ix commented on styles/styles.css
не понятно

2023-03-06 17:47 UTC, U1ix commented on styles/styles.css
> +  margin: 40px 0 30px;
.

2023-03-07 17:48 UTC, merged